name: Automate Dataset Update

on:
  push:
    paths:
      - '**/automate_*.py'
      - 'diabetes_dataset_raw.csv'
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn

      - name: Run automate_Muhammad-Attan.py
        run: python preprocessing/automate_Muhammad-Attan.py

      - name: Commit and push updated dataset
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add preprocessing/diabetes_dataset_processing.csv
          git diff --cached --quiet || git commit -m "Update dataset [auto]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
